### ISSUE TITLE
Dont understand how to install

### ISSUE THREAD

**Issue by Torkess** [gangefors/docker-airdcpp-adlchecker#1]
Hi I have installed gangefors airdcpp before thru docker on a synology nas, pulled the file from registry and made a container and linked the volumes working lika a charm. But cant understand how to install airdcpp-adlchecker. Can't even make a container, and the right place to make a volume. Just get 
Error!="Configuration not found.
I am obviusly new to docker and tried to go through docker tutorials but im not getting much wiser. Is there a more foolproof readme?

**Comment by gangefors** [comment]
If you are using the gangefors/airdcpp-webclient image for your application container then you should be able to use the docker command as it is stated in the README.
Just make sure that you have put a ADLSearch.xml file in the airdcpp configuration directory. If you find DCPlusPlus.xml then this is the directory to put the ADLSearch.xml file in.

Example:
```bash
$ docker run -d --name my-container \
    -e PUID=$(id -u) \
    -e PGID=$(id -g) \
    -v $(pwd)/config:/.airdcpp \
    gangefors/airdcpp-webclient
d440538315b82f9ea28bef148260b4f5b0eabbe46697f1716ec17d36502f5324

$ docker run --rm --volumes-from my-container gangefors/airdcpp-adlchecker --help
usage: adlchecker.py [-h] [--config CONFIG] [--profile PROFILE] [--no-ignore]
                     [--progress] [--no-db]

Perform an ADL search.

options:
  -h, --help         show this help message and exit
  --config CONFIG    Path to the AirDC++ config directory
  --profile PROFILE  The share profile to run the ADL against
  --no-ignore        Do not hide results from ADLSearch.ignorelist
  --progress         Print progress while scanning.
  --no-db            Don't use the FileIndex DB, instead stat files on fs.
```

If you still can't get the adlchecker docker image to work then you need to run the adlsearch.py python script from the configuration folder. There are some limited documentation regarding that in the script itself.
There are limitations running the script with python when running airdcpp in a container due to how share paths are mapped between the host and the container. If your DC share doesn't use the same paths in the container as on the host then the script will not be able to check file sizes correctly (since it uses the path the file have in the DC share when checking the file on the host).
This limitation can be overcome by [installing](https://plyvel.readthedocs.io/en/latest/installation.html) `plyvel`, which is documented in the script itself. Then the script will be using the airdcpp file index DB directly. But if you are not familiar with python or not using linux then I think that you should keep trying to get the docker approach to work.
